#!/bin/bash

# ============================================
# TP Oracle & MySQL - Script Execution Complete
# ============================================

echo "========================================"
echo "  TP ORACLE & MYSQL - EXECUTION COMPLETE"
echo "========================================"
echo ""
echo "Configuration MySQL:"
echo "  - Hote: localhost"
echo "  - Port: 3306"
echo "  - Utilisateur: root"
echo "  - Mot de passe: (aucun)"
echo "  - Enregistrements: 25"
echo ""
echo "Configuration Oracle:"
echo "  - Utilisateur: sys as sysdba"
echo "  - Mot de passe: momenic61"
echo ""
echo "Schema Boutique (ERD):"
echo "  - CLIENT: num, nom, prenom, ddn, tel, genre"
echo "  - ADRESSE: num, rue, cp, ville (1..* par client)"
echo "  - PRODUIT: num, designation, prix, stock"
echo "  - FACTURE: num, num_client, num_produit, qte"
echo ""
echo "========================================"
echo "STRUCTURE DES FICHIERS:"
echo "========================================"
echo ""
echo "Scripts MySQL (scripts_mysql/):"
echo "  01_creation_base.sql"
echo "  02_creation_tables.sql"
echo "  03_procedures_insertion.sql"
echo "  04_execution_insertions.sql"
echo "  05_comparaison_performances.sql"
echo "  06_analyse_et_plan.sql"
echo "  07_script_rapide.sh"
echo ""
echo "Scripts Oracle (scripts_oracle/):"
echo "  01_creation_schema.sql"
echo "  02_creation_tables.sql (avec donnees)"
echo "  03_manipulation_donnees.sql"
echo ""
echo "========================================"
echo "INSTRUCTIONS D'UTILISATION:"
echo "========================================"
echo ""
echo "PARTIE ORACLE:"
echo "--------------"
echo "1. Ouvrir l'invite de commande (cmd ou powershell)"
echo ""
echo "2. Se connecter a SQL*Plus:"
echo "   sqlplus sys/momenic61 as sysdba"
echo ""
echo "3. Creer le schema:"
echo "   @/workspace/scripts_oracle/01_creation_schema.sql"
echo ""
echo "4. Se connecter avec le nouveau compte:"
echo "   CONNECT approvisionnement/approvisionnementeam"
echo "   Mot de passe: approvisionnementeam"
echo ""
echo "5. Creer les tables et inserer les donnees:"
echo "   @/workspace/scripts_oracle/02_creation_tables.sql"
echo ""
echo "6. Executer les manipulations:"
echo "   @/workspace/scripts_oracle/03_manipulation_donnees.sql"
echo ""
echo "PARTIE MYSQL:"
echo "-------------"
echo "Option A - Execution automatique:"
echo "   chmod +x /workspace/scripts_mysql/07_script_rapide.sh"
echo "   ./workspace/scripts_mysql/07_script_rapide.sh"
echo ""
echo "Option B - Execution manuelle:"
echo "   mysql -h localhost -P 3306 -u root"
echo "   source /workspace/scripts_mysql/01_creation_base.sql"
echo "   source /workspace/scripts_mysql/02_creation_tables.sql"
echo "   etc..."
echo ""
echo "========================================"
echo "RESULTATS ATTENDUS:"
echo "========================================"
echo ""
echo "Oracle - Boutique Schema:"
echo "  - 5 clients"
echo "  - 6 adresses"
echo "  - 10 produits"
echo "  - 10 lignes de facture"
echo "  - Vues et procedures creees"
echo ""
echo "MySQL - Comparaison Index:"
echo "  - 75 enregistrements (25 clients, 25 produits, 25 commandes)"
echo "  - 6 tables creees (avec/sans index)"
echo "  - 8 tests de performance"
echo "  - Resultats dans table 'resultats_performance'"
echo ""
echo "========================================"
echo "DOCUMENTATION:"
echo "========================================"
echo ""
echo "Lisez README.md pour:"
echo "  - Guide d'utilisation detaille"
echo "  - Commandes utiles MySQL et Oracle"
echo "  - Depannage"
echo "  - Structure du rapport TP"
echo ""
echo "Lisez TP_Oracle_MySQL_Solutions.md pour:"
echo "  - Toutes les commandes SQL detaillees"
echo "  - Explications des concepts"
echo "  - Exemples de requetes"
echo ""
echo "========================================"
echo "BON COURAGE POUR VOTRE TP !"
echo "========================================"
