#!/bin/bash

# ============================================
# TP Oracle & MySQL - Execution Rapide
# ============================================

echo "========================================"
echo "  TP ORACLE & MYSQL - SOLUTION COMPLETE"
echo "========================================"
echo ""
echo "Configuration MySQL:"
echo "  - Hote: localhost"
echo "  - Port: 3306"
echo "  - Utilisateur: root"
echo "  - Mot de passe: (aucun)"
echo "  - Enregistrements: 25"
echo ""
echo "Configuration Oracle:"
echo "  - Utilisateur: sys as sysdba"
echo "  - Mot de passe: momenic61"
echo ""
echo "Fichiers crees:"
echo "   TP_Oracle_MySQL_Solutions.md (Document complet)"
echo "   README.md (Guide d'utilisation)"
echo ""
echo "Scripts MySQL disponibles dans scripts_mysql/:"
echo "   01_creation_base.sql"
echo "   02_creation_tables.sql"
echo "   03_procedures_insertion.sql"
echo "   04_execution_insertions.sql"
echo "   05_comparaison_performances.sql"
echo "   06_analyse_et_plan.sql"
echo "   07_script_rapide.sh"
echo ""
echo "Scripts Oracle disponibles dans scripts_oracle/:"
echo "   01_creation_schema.sql"
echo "   02_manipulation_donnees.sql"
echo ""
echo "========================================"
echo "POUR DEMARRER:"
echo "========================================"
echo ""
echo "PARTIE 1: ORACLE"
echo "--------------------"
echo "1. Ouvrez l'invite de commande"
echo "2. Executez: sqlplus"
echo "3. Connectez-vous: connect sys/momenic61 as sysdba"
echo "4. Executez le script: @scripts_oracle/01_creation_schema.sql"
echo "5. Exportez les donnees du schema vente (voir README)"
echo "6. Importez dans approvisionnement (voir README)"
echo "7. Manipulez les donnees avec: @scripts_oracle/02_manipulation_donnees.sql"
echo ""
echo "PARTIE 2: MYSQL"
echo "-------------------"
echo "Option A - Execution automatique:"
echo "   chmod +x scripts_mysql/07_script_rapide.sh"
echo "   ./scripts_mysql/07_script_rapide.sh"
echo ""
echo "Option B - Execution manuelle:"
echo "   mysql -h localhost -P 3306 -u root"
echo "   puis executer les scripts dans l'ordre:"
echo "   source scripts_mysql/01_creation_base.sql"
echo "   source scripts_mysql/02_creation_tables.sql"
echo "   etc..."
echo ""
echo "========================================"
echo "CE QUE VOUS ALLEZ OBTENIR:"
echo "========================================"
echo ""
echo "Schema Oracle 'approvisionnement' cree et peuple"
echo "Base MySQL avec 75 enregistrements (25 de chaque)"
echo "8 tests de performance comparatifs"
echo "Tableau recapitulatif des gains/pertes"
echo "Plans d'execution analyses"
echo "Rapport complet pour votre TP"
echo ""
echo "========================================"
echo "DOCUMENTATION:"
echo "========================================"
echo ""
echo "Lisez README.md pour:"
echo "   Guide d'utilisation detaille"
echo "   Commandes utiles"
echo "   Depannage"
echo "   Structure du rapport attendu"
echo ""
echo "========================================"
echo "BON COURAGE POUR VOTRE TP !"
echo "========================================"
